test
invoke changes

install changes

invoke changes

invoke changes

invoke changes

invoke changes

invoke changes

invoke changes

invoke

invoke changes

invoke changes

test

test

test

test

test

test

diff --git a/.github/workflows/check-installation.yml b/.github/workflows/check-installation.yml
--- a/.github/workflows/check-installation.yml
+++ b/.github/workflows/check-installation.yml
@@ -1,7 +1,5 @@
 name: Check installation
-on:
-  push:
-    branches: [ master ]
+on: pull_request
 
 jobs:
   build-publish-containers:
@@ -15,6 +13,8 @@ jobs:
       - name: Install Invoke-AtomicRedTeam
         shell: pwsh
         run: |
-          echo  ${{ github.event.pull_request }}
-          IEX (IWR 'https://raw.githubusercontent.com/cyberbuff/invoke-atomicredteam/master/install-atomicsfolder.ps1' -UseBasicParsing);
-          Install-AtomicsFolder
+          IEX (IWR 'https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/install-atomicredteam.ps1' -UseBasicParsing);
+          Install-AtomicRedTeam -RepoOwner "${{ github.event.pull_request.head.repo.owner.login }}" -Branch "${{ github.event.pull_request.head.ref }}" -getAtomics -Force -noPayloads
+          if($error.contains("Installation of AtomicRedTeam Failed")){
+            exit 1
+          }
